### ISSUE TITLE
Allow to use regular dice instead of "fair" dice

### ISSUE THREAD

**Issue by A4Vision** [shirbenisrael/CatanDice#1]
היי שיר,
אנחנו משתמשים באפליקציה שלך כל שבת
זה כיף גדול
תוכל בבקשה להוסיף אפשרות להשתמש בקוביות רגילות, במקום בקוביות הוגנות ?
אני מתכוון להוסיף מימוש נאיבי ללוגיקה שבפונקציה
https://github.com/shirbenisrael/CatanDice/blob/master/app/src/main/java/com/shirbi/catandice/Logic.java#L66
ולהוסיף אפשרות לבחור בקוביות רגילות בחלון של ההגדרות

בברכה,
אסף

**Comment by shirbenisrael** [comment]
אפשרי, אבל אז במה זה יותר טוב מקוביות רגילות פיזיות? רק בשביל לעקוב אחרי ההיסטוגרמה ואחרי מיקום הספינה במשחק עם הערים והאבירים?

**Comment by A4Vision** [comment]
היי שיר,
זה משמעותית יותר מהיר ונוח וגם משמעותית יותר הוגן

בקוביות פיסיות, כששחקן מרים את הקוביות ולא משקיע הרבה זמן בעירבוב, הוא מטיל וההטלה לא הוגנת
למשל, תופעה משמעותית היא רצפים של 7, בגלל המבנה של הקוביה הפיסית
(הסכום של שתי פיאות נגדיות הוא 7)

בקוביות פיסיות לוקח הרבה זמן להטיל, ובכל 
 פעם שהקוביה נופלת באלכסון על כלי משחק אז יש וויכוח.

האפליקציה שבנית מאוד נוחה והיא הרבה יותר טובה מכל האחרות כי הממשק פשוט, הקוביות גדולות ואתה תומך בהרחבה

אנחנו משתמשים באפליקציה שלך בעיקר בזכות  המהירות, ולא בגלל ההגינות. למעשה, עד אתמול הייתי בטוח שהקוביות שלך הן רגילות.
בינתיים חזרנו להשתמש בקוביות פיסיות כי גילינו איך הקוביות שלך עובדות

אגב, אם אתה כבר בעניין של להוסיף עוד פיצ'רים, אז כפתור להגרלה של מספר בהתפלגות אחידה יכול להיות שימושי בשביל לגנוב קלף כשהrobber תוקף
אצלנו הקלפים של ההרחבה חדשים והמקוריים בלויים ולכן אנחנו זורקים קוביה כדי לבחור
בכל אופן, זה הרבה פחות חשוב מהאלגוריתם של הקוביות.

**Comment by shirbenisrael** [comment]
אחלה. אני אוסיף את התמיכה בקוביות ללא הגינות מיוחדת.
לגבי התפלגות אחידה בשביל לבחור קלף כאשר צריך לשדוד - הפיתרון שלי הוא שהשחקן הנשדד מצהיר על מספר הקלפים שבידו, ואז אוסף אותם לערימה, ואז השחקן השודד בוחר מספר מ-1 ועד מספר הקלפים, והנשדד נותן לו את הקלף המתאים מהערימה שבידו.
כך אי אפשר לראות אילו קלפים שחוקים ואילו לא.

**Comment by shirbenisrael** [comment]
מימשתי את הפיצ'ר החדש והעלתי מחדש לחנות של גוגל. זה אמור להתקין את הגרסה החדשה תוך שעות ספורות.

**Comment by A4Vision** [comment]
תודה שיר, העדכון מעולה !!!

**Comment by A4Vision** [comment]
לגבי הגרלה בהתפלגות אחידה במקרה של שוד
אנחנו זורקים קוביה כדי למנוע אפשרות למניפולציה
בכל אופן, זה פחות קריטי

**Comment by shirbenisrael** [comment]
תודה. בבקשה תן דירוג 5 לאפליקציה :-)

**Comment by A4Vision** [comment]
ברור, נתתי עוד לפני שביקשת ואמרתי גם למשפחה שלי לתת

**Comment by shirbenisrael** [comment]
תודה :-)
